# Generated by Django 4.1.2 on 2023-03-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='CarClassSUb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('car_sub', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='pages.carclass', verbose_name='title')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
