# Generated by Django 4.1.2 on 2023-03-30 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_carclass_carclasssub_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carclasssub',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='carclasssub',
            name='car_sub',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='pages.carclass', verbose_name='sub'),
        ),
    ]
