# Generated by Django 4.1.2 on 2023-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_carclasssub_title_alter_carclasssub_car_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='carclass',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
