# Generated by Django 4.1.2 on 2023-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_carclass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carclasssub',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
