# Generated by Django 4.1.2 on 2023-04-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_carclasssub_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carclass',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='carclasssub',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/image'),
        ),
    ]
