# Generated by Django 4.1.2 on 2023-04-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_carclass_image_alter_carclasssub_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='media/image')),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='media/image')),
            ],
        ),
        migrations.AlterField(
            model_name='carclass',
            name='title',
            field=models.CharField(max_length=100, verbose_name='car class'),
        ),
        migrations.DeleteModel(
            name='CarClassSUb',
        ),
        migrations.AddField(
            model_name='carbrand',
            name='car_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_class', to='pages.carclass', verbose_name='car class'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='pages.carbrand', verbose_name='brand'),
        ),
    ]
