# Generated by Django 4.1.2 on 2023-04-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date time created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date time modified'),
        ),
    ]
